const ActionsTypes = {
  INCREASE_COUNTER : 'INCREASE_COUNTER',
  DECREASE_COUNTER : 'DECREASE_COUNTER',
  RESET_COUNTER:'RESET_COUNTER',

  ASYNC_INCREMENT : 'ASYNC_INCREMENT',
  ASYNC_DECEMENT :'ASYNC_DECEMENT,'
}

export default ActionsTypes;